### PR TITLE
Switch to go modules

### PR DESCRIPTION
**Pull request by loafoe**
This PR switches the project from from dep to go modules for dependency management. It also upgrades the Dockerfile images to use Go 1.12.1

### CODE REVIEW

**Comment by eug48** [comment]
Thanks very much. I just need to learn a bit more about go modules before I merge this.

By the way, what tools did you use to do the migration? Have any packages been upgraded? For example, I've noticed that cloud.google.com/go is in go.sum but wasn't in the dep lockfile.

**Comment by loafoe** [comment]
Hi @eug48 , many thanks for maintaining this project! 

I just used the standard `go mod` tool. Basically:

```
$ go mod init
go: creating new go.mod: module github.com/eug48/fhir
go: copying requirements from Gopkg.lock
```

This step examines the existing `Gopkg.*` files and writes out ` new `go.mod` file. I added the line:

`replace github.com/eug48/fhir v0.0.0 => /`

The only version tweak I did was to force `github.com/mongodb/mongo-go-driver` to version `v0.0.12`. For some reason the conversion pinned it to `v1.0.0`which is incompatible. 
Initially I tried to port the code to use the`v1.0.0` of the mongo driver but this was a bridge too far especially since my mongo skills are `nil` :)

Ultimately I want to contribute to adding PostgreSQL support. 

The `cloud.google.com/go` dependency is coming from below:

```
$ go mod graph|grep cloud.google.com/go
golang.org/x/oauth2@v0.0.0-20190319182350-c85d3e98c914 cloud.google.com/go@v0.34.0
```

**Comment by eug48** [comment]
Ok looks good & the tests pass. I'll merge it now - thanks!

PostgreSQL support would be brilliant. You might have noticed I've jotted down some ideas in this repository - but please don't feel constrained by them. One thing I've thought about since then is that it would be great to develop PostgreSQL support with a view to also enabling SQLite support at some point. SQLite would be very useful for running this server on end-user devices, and for testing/CI use-cases.

**Comment by eug48** [comment]
I've had to revert this since when under concurrent load HTTP responses were being intermittently concatenated with those from other requests... Not sure why yet. It may have something to do with my new FileLoggerMiddleware & some dependency upgrades as a result of this PR.

**Comment by eug48** [comment]
I think I've got it done in 16306ba without problems under load
The new version of `go mod init` looks to have preserved the correct version of gin from Gopkg.lock

**Pull request merged**
